services:
  backend:
    image: backend:latest
    # restart: always
    networks:
      - prod-network
    env_file:
      - .env
    ports:
      - "6543:80"
    environment:
      - ENV_FILE='.env'

    build:
      context: .
    platform: linux/amd64

    volumes:
      - ./app:/app/app

volumes:
  app-db-data:


networks:
  prod-network:
    name: prod-network
    driver: bridge